# Primary accent for interactive elements
# primaryColor = '#7792E3'

# Background color for the main content area
# backgroundColor = '#273346'

# Background color for sidebar and most interactive widgets
# secondaryBackgroundColor = '#B9F1C0'

# Color used for almost all text
# textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
# font = "sans serif"

[theme]
base = "light"
primaryColor="#25c19f"
backgroundColor="#2b3137"
secondaryBackgroundColor="#586e75"
textColor="#fafafa"
font="monospace"

[client]
showSidebarNavigation = false



